/**
 * Curated architectural nodes/edges for GardenFervor Project Graph.
 * Only HIGH/MEDIUM relations with verifiable sources.
 * FUTURE / UNVERIFIED must keep confidence !== HIGH unless documented as intentional future.
 */

export const CURATED_VERSION = '1.0.0';

/** @typedef {'GOVERNANCE'|'DESIGN_GATE'|'CONTRACTS'|'WORLD_TERRAIN'|'SPATIAL'|'PROJECTS_TASKS'|'UNITS_EXECUTION'|'ECONOMY_RESOURCES'|'BUILDINGS_INFRA'|'UI_INPUT'|'GAME_DEMO'|'DATA'|'VALIDATION'|'CONTENT_EXTERNAL'|'TOOLING'} Category */

/**
 * @type {Array<object>}
 */
export const curatedNodes = [
  // ——— GOVERNANCE ———
  {
    id: 'gov_regles',
    name: 'REGLES_PROJET',
    category: 'GOVERNANCE',
    designStatus: 'VALIDÉ',
    implementationStatus: 'n/a',
    validationStatus: 'n/a',
    responsibility: 'Règles opérationnelles permanentes du projet',
    sourceDocuments: ['REGLES_PROJET.md'],
    sourceFiles: [],
    evidence: [],
    confidence: 'HIGH',
  },
  {
    id: 'gov_etat',
    name: 'ETAT_PROJET',
    category: 'GOVERNANCE',
    designStatus: 'VALIDÉ',
    implementationStatus: 'n/a',
    validationStatus: 'n/a',
    responsibility: 'État officiel courant (jalons, preuves, contrats)',
    sourceDocuments: ['ETAT_PROJET.md'],
    sourceFiles: [],
    evidence: [],
    confidence: 'HIGH',
    notes: 'Peut diverger du suivi contrats ; le graphe signale les écarts.',
  },
  {
    id: 'gov_historique',
    name: 'HISTORIQUE_MODIFICATIONS',
    category: 'GOVERNANCE',
    designStatus: 'VALIDÉ',
    implementationStatus: 'n/a',
    validationStatus: 'n/a',
    responsibility: 'Journal des modifications et preuves',
    sourceDocuments: ['HISTORIQUE_MODIFICATIONS.md'],
    sourceFiles: [],
    evidence: [],
    confidence: 'HIGH',
  },
  {
    id: 'gov_registre_contrats',
    name: 'Registre des contrats',
    category: 'GOVERNANCE',
    designStatus: 'VALIDÉ',
    implementationStatus: 'n/a',
    validationStatus: 'PASS',
    responsibility: 'Inventaire, ordre, nécessité des contrats C-00…C-23',
    sourceDocuments: ['CONTRATS/00_REGISTRE_CONTRATS.md'],
    sourceFiles: [],
    evidence: [],
    confidence: 'HIGH',
  },
  {
    id: 'gov_suivi_contrats',
    name: 'Suivi production contrats',
    category: 'GOVERNANCE',
    designStatus: 'VALIDÉ',
    implementationStatus: 'n/a',
    validationStatus: 'n/a',
    responsibility: 'Avancement documentaire des contrats (2/16)',
    sourceDocuments: ['CONTRATS/00_SUIVI_CONTRATS.md'],
    sourceFiles: [],
    evidence: [],
    confidence: 'HIGH',
  },

  // ——— DESIGN GATE ———
  {
    id: 'dg_hub',
    name: 'Design Gate (ensemble)',
    category: 'DESIGN_GATE',
    designStatus: 'VALIDÉ',
    implementationStatus: 'n/a',
    validationStatus: 'PASS',
    responsibility: 'Décisions de conception DG-00 → DG-14',
    sourceDocuments: [
      'GardenFervor_DesignGate_React/src/data/designGate.js',
      'ETAT_PROJET.md',
    ],
    sourceFiles: ['GardenFervor_DesignGate_React/'],
    evidence: [],
    confidence: 'HIGH',
    notes: 'Sections DG-00…DG-14 clôturées VALIDÉ (ETAT_PROJET).',
  },
  {
    id: 'dg_00',
    name: 'DG-00 Cadre',
    category: 'DESIGN_GATE',
    designStatus: 'VALIDÉ',
    implementationStatus: 'n/a',
    validationStatus: 'PASS',
    responsibility: 'Identité RTS, périmètre simulation, lexique',
    sourceDocuments: ['GardenFervor_DesignGate_React/src/data/designGate.js'],
    sourceFiles: [],
    evidence: [],
    confidence: 'HIGH',
  },
  {
    id: 'dg_04',
    name: 'DG-04 Autonomie unités',
    category: 'DESIGN_GATE',
    designStatus: 'VALIDÉ',
    implementationStatus: 'PARTIAL',
    validationStatus: 'PASS',
    responsibility: 'Sélection tâche, exécution, replanification unité',
    sourceDocuments: ['GardenFervor_DesignGate_React/src/data/designGate.js'],
    sourceFiles: [],
    evidence: ['evid_odc_f5'],
    confidence: 'HIGH',
  },
  {
    id: 'dg_05',
    name: 'DG-05 Ressources / économie',
    category: 'DESIGN_GATE',
    designStatus: 'VALIDÉ',
    implementationStatus: 'PARTIAL',
    validationStatus: 'PASS',
    responsibility: 'Taxonomie ressources, stocks, réservations (conception)',
    sourceDocuments: ['GardenFervor_DesignGate_React/src/data/designGate.js'],
    sourceFiles: [],
    evidence: ['evid_odc_f6'],
    confidence: 'HIGH',
  },
  {
    id: 'dg_06',
    name: 'DG-06 Logistique',
    category: 'DESIGN_GATE',
    designStatus: 'VALIDÉ',
    implementationStatus: 'PARTIAL',
    validationStatus: 'PASS',
    responsibility: 'Transport / accès réseaux (conception)',
    sourceDocuments: ['GardenFervor_DesignGate_React/src/data/designGate.js'],
    sourceFiles: [],
    evidence: ['evid_odc_f7'],
    confidence: 'HIGH',
  },
  {
    id: 'dg_08',
    name: 'DG-08 Terrain / terraform',
    category: 'DESIGN_GATE',
    designStatus: 'VALIDÉ',
    implementationStatus: 'PARTIAL',
    validationStatus: 'PASS',
    responsibility: 'État terrain, Raise/Lower/Paint, conséquences',
    sourceDocuments: ['GardenFervor_DesignGate_React/src/data/designGate.js'],
    sourceFiles: [],
    evidence: ['evid_odc_f8'],
    confidence: 'HIGH',
  },
  {
    id: 'dg_09',
    name: 'DG-09 Environnement / écosystèmes',
    category: 'DESIGN_GATE',
    designStatus: 'VALIDÉ',
    implementationStatus: 'STUB',
    validationStatus: 'n/a',
    responsibility: 'Eau, sol, végétation (conception ; stubs spatiaux)',
    sourceDocuments: ['GardenFervor_DesignGate_React/src/data/designGate.js'],
    sourceFiles: [],
    evidence: ['evid_odc_f3'],
    confidence: 'HIGH',
  },
  {
    id: 'dg_11',
    name: 'DG-11 Chantiers procéduraux',
    category: 'DESIGN_GATE',
    designStatus: 'VALIDÉ',
    implementationStatus: 'PARTIAL',
    validationStatus: 'PASS',
    responsibility: 'Projet, tâches, réaction 11.6, fin de chantier',
    sourceDocuments: ['GardenFervor_DesignGate_React/src/data/designGate.js'],
    sourceFiles: [],
    evidence: ['evid_odc_f4', 'evid_s3_cohort'],
    confidence: 'HIGH',
  },
  {
    id: 'dg_11_6',
    name: 'DG-11.6 Réaction chantier',
    category: 'DESIGN_GATE',
    designStatus: 'VALIDÉ',
    implementationStatus: 'PLANNED',
    validationStatus: 'n/a',
    responsibility: 'Recalcul / suspension / blocage au niveau chantier',
    sourceDocuments: ['GardenFervor_DesignGate_React/src/data/designGate.js'],
    sourceFiles: [],
    evidence: [],
    confidence: 'HIGH',
    notes: 'Complémentaire au mécanisme tâche (futur C-04) ; pas d’implémentation dédiée observée.',
  },
  {
    id: 'dg_13',
    name: 'DG-13 UX / lisibilité',
    category: 'DESIGN_GATE',
    designStatus: 'VALIDÉ',
    implementationStatus: 'PARTIAL',
    validationStatus: 'n/a',
    responsibility: 'Lisibilité unités / blocages / progression',
    sourceDocuments: ['GardenFervor_DesignGate_React/src/data/designGate.js'],
    sourceFiles: [],
    evidence: [],
    confidence: 'HIGH',
  },

  // ——— CONTRACTS (from registre + suivi; files only when present) ———
  mkContract('c_00', 'C-00', 'Cadre / invariants', 'NON REQUIS', 'NON COMMENCÉ', 'I', false, null),
  mkContract('c_01', 'C-01', 'Terrain runtime', 'REQUIS', 'VALIDÉ', 'P', true, 'CONTRATS/C-01_TERRAIN_RUNTIME.md', {
    notes: 'Contrat VALIDÉ ; dettes d’implémentation documentées (F1, persist, dirty Soil/Water…).',
  }),
  mkContract('c_02', 'C-02', 'Substrat spatial', 'REQUIS', 'VALIDÉ', 'P', true, 'CONTRATS/C-02_SUBSTRAT_SPATIAL.md', {
    notes: '31 décisions A1–F3 ; contrat VALIDÉ.',
  }),
  mkContract('c_03', 'C-03', 'Intention → Project', 'SUFFISANT*', 'NON COMMENCÉ', 'I', false, null, {
    notes: 'Addendum fermé pour S3 ; hors compteur 16 tant que non ouvert.',
  }),
  mkContract('c_04', 'C-04', 'Tâches / graphe / dépendances', 'PARTIEL', 'NON COMMENCÉ', 'I', true, null, {
    notes: 'Prochain contrat obligatoire du compteur 16 après C-02 ; proposition 48 décisions non inscrite.',
  }),
  mkContract('c_05', 'C-05', 'WorkSite / SitePrep', 'PARTIEL→REQUIS', 'NON COMMENCÉ', 'P', true, null, {
    notes: 'Cas A validé cohorte ; Case B suspendu.',
  }),
  mkContract('c_06', 'C-06', 'Capacités / roster', 'SUFFISANT*', 'NON COMMENCÉ', 'I', false, null),
  mkContract('c_07', 'C-07', 'Autonomie unité', 'PARTIEL', 'NON COMMENCÉ', 'I', true, null),
  mkContract('c_08', 'C-08', 'Terraformer opérationnel', 'REQUIS', 'NON COMMENCÉ', 'P', true, null, {
    notes: 'Bloque Demo Case B.',
  }),
  mkContract('c_09', 'C-09', 'Économie physique', 'SUFFISANT*', 'NON COMMENCÉ', 'I', false, null),
  mkContract('c_10', 'C-10', 'Stocks localisés A/B', 'SUFFISANT*', 'NON COMMENCÉ', 'I', false, null),
  mkContract('c_11', 'C-11', 'Réservations', 'PARTIEL', 'NON COMMENCÉ', 'P', true, null),
  mkContract('c_12', 'C-12', 'Transport / logistique', 'PARTIEL', 'NON COMMENCÉ', 'P', true, null),
  mkContract('c_13', 'C-13', 'Construction / En service', 'SUFFISANT*', 'NON COMMENCÉ', 'I', false, null),
  mkContract('c_14', 'C-14', 'Infrastructures', 'REQUIS', 'NON COMMENCÉ', 'N', true, null),
  mkContract('c_15', 'C-15', 'Hydrologie', 'REQUIS', 'NON COMMENCÉ', 'N/P', true, null),
  mkContract('c_16', 'C-16', 'Sol', 'REQUIS', 'NON COMMENCÉ', 'N/P', true, null),
  mkContract('c_17', 'C-17', 'Végétation / écosystèmes', 'PARTIEL→REQUIS', 'NON COMMENCÉ', 'N', true, null),
  mkContract('c_18', 'C-18', 'Technologie / progression', 'PARTIEL', 'NON COMMENCÉ', 'P', true, null),
  mkContract('c_19', 'C-19', 'Persistance / sauvegarde', 'REQUIS', 'NON COMMENCÉ', 'N/P', true, null),
  mkContract('c_20', 'C-20', 'Observabilité / UX', 'PARTIEL', 'NON COMMENCÉ', 'P', true, null),
  mkContract('c_21', 'C-21', 'Simulation / fréquences', 'PARTIEL', 'NON COMMENCÉ', 'P', true, null),
  mkContract('c_22', 'C-22', 'Investor Demo', 'NON REQUIS', 'NON COMMENCÉ', 'I', false, null),
  mkContract('c_23', 'C-23', 'Présentation M4 / UDS', 'NON REQUIS', 'NON COMMENCÉ', 'I', false, null),

  // ——— SYSTEMS ———
  {
    id: 'sys_landscape_terraform',
    name: 'LandscapeTerraformSubsystem',
    category: 'WORLD_TERRAIN',
    designStatus: 'VALIDÉ',
    implementationStatus: 'PARTIAL',
    validationStatus: 'PARTIAL',
    responsibility: 'Brushes runtime LandscapeEdit ; pont Spatial dirty',
    sourceFiles: [
      'Source/GardenFervor/RTS/Terraform/GardenFervorLandscapeTerraformSubsystem.h',
      'Source/GardenFervor/RTS/Terraform/GardenFervorLandscapeTerraformSubsystem.cpp',
    ],
    sourceDocuments: ['CONTRATS/C-01_TERRAIN_RUNTIME.md'],
    evidence: ['evid_odc_f8'],
    confidence: 'HIGH',
  },
  {
    id: 'sys_runtime_store',
    name: 'RuntimeTerraformStore',
    category: 'WORLD_TERRAIN',
    designStatus: 'VALIDÉ',
    implementationStatus: 'PARTIAL',
    validationStatus: 'INVALIDÉ',
    responsibility: 'Store hauteur CPU / extents Spatial ; overlay PMC inactif',
    sourceFiles: [
      'Source/GardenFervor/RTS/Terraform/GardenFervorRuntimeTerraformStore.h',
      'Source/GardenFervor/RTS/Terraform/GardenFervorRuntimeTerraformStore.cpp',
    ],
    sourceDocuments: ['CONTRATS/C-01_TERRAIN_RUNTIME.md', 'Saved/ODC_F1_RuntimeTerrainGate.txt'],
    evidence: ['evid_odc_f1'],
    confidence: 'HIGH',
    notes: 'ODC-F1 INVALIDÉ ; shipping Base+Delta À REFAIRE.',
  },
  {
    id: 'sys_base_height',
    name: 'IslandBaseHeightData',
    category: 'WORLD_TERRAIN',
    designStatus: 'VALIDÉ',
    implementationStatus: 'IMPLEMENTED',
    validationStatus: 'PARTIAL',
    responsibility: 'Données hauteur de base île',
    sourceFiles: [
      'Source/GardenFervor/RTS/Terraform/GardenFervorIslandBaseHeightData.h',
      'Source/GardenFervor/RTS/Terraform/GardenFervorIslandBaseHeightData.cpp',
    ],
    sourceDocuments: ['CONTRATS/C-01_TERRAIN_RUNTIME.md'],
    evidence: [],
    confidence: 'HIGH',
  },
  {
    id: 'sys_terraform_visualizer',
    name: 'RuntimeTerraformVisualizer',
    category: 'WORLD_TERRAIN',
    designStatus: 'VALIDÉ',
    implementationStatus: 'LEGACY',
    validationStatus: 'n/a',
    responsibility: 'Overlay PMC (inactif — bUseRuntimeTerraformOverlay=False)',
    sourceFiles: [
      'Source/GardenFervor/RTS/Terraform/GardenFervorRuntimeTerraformVisualizer.h',
      'Source/GardenFervor/RTS/Terraform/GardenFervorRuntimeTerraformVisualizer.cpp',
    ],
    sourceDocuments: ['Saved/ODC_F1_RuntimeTerrainGate.txt'],
    evidence: ['evid_odc_f1'],
    confidence: 'HIGH',
  },
  {
    id: 'sys_terraform_collision',
    name: 'RuntimeTerraformCollision',
    category: 'WORLD_TERRAIN',
    designStatus: 'VALIDÉ',
    implementationStatus: 'LEGACY',
    validationStatus: 'n/a',
    responsibility: 'Collision overlay (inactif avec PMC)',
    sourceFiles: [
      'Source/GardenFervor/RTS/Terraform/GardenFervorRuntimeTerraformCollision.h',
      'Source/GardenFervor/RTS/Terraform/GardenFervorRuntimeTerraformCollision.cpp',
    ],
    sourceDocuments: ['Saved/ODC_F1_RuntimeTerrainGate.txt'],
    evidence: [],
    confidence: 'HIGH',
  },
  {
    id: 'sys_terraform_save',
    name: 'TerraformSaveGame',
    category: 'WORLD_TERRAIN',
    designStatus: 'VALIDÉ',
    implementationStatus: 'SUSPENDED',
    validationStatus: 'n/a',
    responsibility: 'Persistance terraform (bEnableRuntimeTerraformPersistence=False)',
    sourceFiles: [
      'Source/GardenFervor/RTS/Terraform/GardenFervorTerraformSaveGame.h',
      'Source/GardenFervor/RTS/Terraform/GardenFervorTerraformSaveGame.cpp',
    ],
    sourceDocuments: ['Saved/ODC_F1_RuntimeTerrainGate.txt'],
    evidence: ['evid_odc_f1'],
    confidence: 'HIGH',
  },
  {
    id: 'sys_spatial',
    name: 'SpatialSubsystem',
    category: 'SPATIAL',
    designStatus: 'VALIDÉ',
    implementationStatus: 'PARTIAL',
    validationStatus: 'PASS',
    responsibility: 'Grille cellules, dirty, queries Terrain/Soil/Water',
    sourceFiles: [
      'Source/GardenFervor/RTS/Spatial/GardenFervorSpatialSubsystem.h',
      'Source/GardenFervor/RTS/Spatial/GardenFervorSpatialSubsystem.cpp',
      'Source/GardenFervor/RTS/Spatial/GardenFervorSpatialTypes.h',
    ],
    sourceDocuments: ['CONTRATS/C-02_SUBSTRAT_SPATIAL.md'],
    evidence: ['evid_odc_f3'],
    confidence: 'HIGH',
  },
  {
    id: 'sys_project',
    name: 'ProjectSubsystem',
    category: 'PROJECTS_TASKS',
    designStatus: 'VALIDÉ',
    implementationStatus: 'IMPLEMENTED',
    validationStatus: 'PASS',
    responsibility: 'Projects, Expand*, SitePrep helpers, cohorte S3',
    sourceFiles: [
      'Source/GardenFervor/RTS/Projects/GardenFervorProjectSubsystem.h',
      'Source/GardenFervor/RTS/Projects/GardenFervorProjectSubsystem.cpp',
      'Source/GardenFervor/RTS/Projects/GardenFervorProjectTypes.h',
    ],
    sourceDocuments: ['CONTRATS/00_REGISTRE_CONTRATS.md'],
    evidence: ['evid_odc_f4', 'evid_s3_cohort'],
    confidence: 'HIGH',
  },
  {
    id: 'sys_siteprep',
    name: 'SitePrep helpers / types',
    category: 'PROJECTS_TASKS',
    designStatus: 'VALIDÉ',
    implementationStatus: 'PARTIAL',
    validationStatus: 'PASS',
    responsibility: 'bSiteReady, ApplySitePreparation, Cas A/B (B suspendu)',
    sourceFiles: [
      'Source/GardenFervor/RTS/Projects/GardenFervorSitePrepTypes.h',
      'Source/GardenFervor/RTS/Projects/GardenFervorSitePrepHelpers.h',
      'Source/GardenFervor/RTS/Projects/GardenFervorSitePrepHelpers.cpp',
    ],
    sourceDocuments: ['CONTRATS/00_REGISTRE_CONTRATS.md'],
    evidence: ['evid_s3_cohort'],
    confidence: 'HIGH',
  },
  {
    id: 'sys_task',
    name: 'TaskSubsystem',
    category: 'PROJECTS_TASKS',
    designStatus: 'PARTIAL',
    implementationStatus: 'IMPLEMENTED',
    validationStatus: 'PASS',
    responsibility: 'Graphe tâches, readiness, claim, progress, réservations tâche',
    sourceFiles: [
      'Source/GardenFervor/RTS/Tasks/GardenFervorTaskSubsystem.h',
      'Source/GardenFervor/RTS/Tasks/GardenFervorTaskSubsystem.cpp',
      'Source/GardenFervor/RTS/Tasks/GardenFervorTaskTypes.h',
    ],
    sourceDocuments: ['CONTRATS/00_REGISTRE_CONTRATS.md', 'Saved/ODC_F4_TaskGraphGate.txt'],
    evidence: ['evid_odc_f4'],
    confidence: 'HIGH',
    notes: 'Contrat C-04 non rédigé ; runtime S3 opérationnel.',
  },
  {
    id: 'sys_unit_base',
    name: 'UnitBase',
    category: 'UNITS_EXECUTION',
    designStatus: 'VALIDÉ',
    implementationStatus: 'IMPLEMENTED',
    validationStatus: 'PASS',
    responsibility: 'Acteur unité RTS',
    sourceFiles: [
      'Source/GardenFervor/RTS/Units/GardenFervorUnitBase.h',
      'Source/GardenFervor/RTS/Units/GardenFervorUnitBase.cpp',
    ],
    sourceDocuments: [],
    evidence: ['evid_s3_cohort'],
    confidence: 'HIGH',
  },
  {
    id: 'sys_unit_agent',
    name: 'UnitTaskAgent',
    category: 'UNITS_EXECUTION',
    designStatus: 'VALIDÉ',
    implementationStatus: 'IMPLEMENTED',
    validationStatus: 'PASS',
    responsibility: 'Seek→Claim→Execute→Verify→Complete ; InstantMode',
    sourceFiles: [
      'Source/GardenFervor/RTS/Units/GardenFervorUnitTaskAgent.h',
      'Source/GardenFervor/RTS/Units/GardenFervorUnitTaskAgent.cpp',
    ],
    sourceDocuments: ['REGLES_PROJET.md'],
    evidence: ['evid_odc_f5', 'evid_s3_cohort'],
    confidence: 'HIGH',
  },
  {
    id: 'sys_terraform_tool',
    name: 'TerraformToolComponent',
    category: 'UNITS_EXECUTION',
    designStatus: 'VALIDÉ',
    implementationStatus: 'PARTIAL',
    validationStatus: 'PASS',
    responsibility: 'Outil terraform unité → brushes',
    sourceFiles: [
      'Source/GardenFervor/RTS/Units/GardenFervorTerraformToolComponent.h',
      'Source/GardenFervor/RTS/Units/GardenFervorTerraformToolComponent.cpp',
    ],
    sourceDocuments: [],
    evidence: ['evid_odc_f8'],
    confidence: 'HIGH',
  },
  {
    id: 'sys_harvest',
    name: 'HarvestComponent',
    category: 'UNITS_EXECUTION',
    designStatus: 'VALIDÉ',
    implementationStatus: 'IMPLEMENTED',
    validationStatus: 'PASS',
    responsibility: 'Récolte / extract matière',
    sourceFiles: [
      'Source/GardenFervor/RTS/Units/GardenFervorHarvestComponent.h',
      'Source/GardenFervor/RTS/Units/GardenFervorHarvestComponent.cpp',
    ],
    sourceDocuments: [],
    evidence: ['evid_s3_cohort'],
    confidence: 'HIGH',
  },
  {
    id: 'sys_physical_economy',
    name: 'PhysicalEconomySubsystem',
    category: 'ECONOMY_RESOURCES',
    designStatus: 'VALIDÉ',
    implementationStatus: 'IMPLEMENTED',
    validationStatus: 'PASS',
    responsibility: 'Stocks physiques, Deposit/Withdraw, ResourceKey',
    sourceFiles: [
      'Source/GardenFervor/RTS/Economy/GardenFervorPhysicalEconomySubsystem.h',
      'Source/GardenFervor/RTS/Economy/GardenFervorPhysicalEconomySubsystem.cpp',
      'Source/GardenFervor/RTS/Economy/GardenFervorPhysicalResourceTypes.h',
    ],
    sourceDocuments: [],
    evidence: ['evid_odc_f6', 'evid_s3_cohort'],
    confidence: 'HIGH',
  },
  {
    id: 'sys_economy_component',
    name: 'EconomyComponent',
    category: 'ECONOMY_RESOURCES',
    designStatus: 'PARTIAL',
    implementationStatus: 'LEGACY',
    validationStatus: 'n/a',
    responsibility: 'Économie abstraite / placement (legacy FWSG parallèle PE)',
    sourceFiles: [
      'Source/GardenFervor/RTS/Economy/GardenFervorEconomyComponent.h',
      'Source/GardenFervor/RTS/Economy/GardenFervorEconomyComponent.cpp',
    ],
    sourceDocuments: [],
    evidence: [],
    confidence: 'HIGH',
    notes: 'Présent ; cohorte S3 privilégie PhysicalEconomy.',
  },
  {
    id: 'sys_buildings_placement',
    name: 'BuildingPlacementComponent',
    category: 'BUILDINGS_INFRA',
    designStatus: 'VALIDÉ',
    implementationStatus: 'PARTIAL',
    validationStatus: 'n/a',
    responsibility: 'Placement bâtiments',
    sourceFiles: [
      'Source/GardenFervor/RTS/Buildings/GardenFervorBuildingPlacementComponent.h',
      'Source/GardenFervor/RTS/Buildings/GardenFervorBuildingPlacementComponent.cpp',
    ],
    sourceDocuments: [],
    evidence: [],
    confidence: 'HIGH',
  },
  {
    id: 'sys_production_queue',
    name: 'ProductionQueueComponent',
    category: 'BUILDINGS_INFRA',
    designStatus: 'PARTIAL',
    implementationStatus: 'PARTIAL',
    validationStatus: 'n/a',
    responsibility: 'File de production',
    sourceFiles: [
      'Source/GardenFervor/RTS/Production/GardenFervorProductionQueueComponent.h',
      'Source/GardenFervor/RTS/Production/GardenFervorProductionQueueComponent.cpp',
    ],
    sourceDocuments: [],
    evidence: [],
    confidence: 'HIGH',
  },
  {
    id: 'sys_tech',
    name: 'TechComponent',
    category: 'BUILDINGS_INFRA',
    designStatus: 'PARTIAL',
    implementationStatus: 'PARTIAL',
    validationStatus: 'n/a',
    responsibility: 'Progression / ages (legacy catalogue)',
    sourceFiles: [
      'Source/GardenFervor/RTS/Tech/GardenFervorTechComponent.h',
      'Source/GardenFervor/RTS/Tech/GardenFervorTechComponent.cpp',
    ],
    sourceDocuments: [],
    evidence: [],
    confidence: 'HIGH',
  },
  {
    id: 'sys_rts_catalog',
    name: 'RTSCatalog / Definitions',
    category: 'DATA',
    designStatus: 'PARTIAL',
    implementationStatus: 'IMPLEMENTED',
    validationStatus: 'n/a',
    responsibility: 'DataAssets unités, bâtiments, ressources, tech ages',
    sourceFiles: [
      'Source/GardenFervor/RTS/Data/GardenFervorRTSCatalog.h',
      'Source/GardenFervor/RTS/Data/GardenFervorUnitDefinition.h',
      'Source/GardenFervor/RTS/Data/GardenFervorBuildingDefinition.h',
      'Source/GardenFervor/RTS/Data/GardenFervorResourceDefinition.h',
      'Source/GardenFervor/RTS/Data/GardenFervorTechAgeDefinition.h',
      'Source/GardenFervor/RTS/Data/GardenFervorUnitCapabilityTypes.h',
    ],
    sourceDocuments: [],
    evidence: [],
    confidence: 'HIGH',
  },
  {
    id: 'sys_selection',
    name: 'SelectionComponent',
    category: 'UI_INPUT',
    designStatus: 'PARTIAL',
    implementationStatus: 'IMPLEMENTED',
    validationStatus: 'n/a',
    responsibility: 'Sélection unités',
    sourceFiles: [
      'Source/GardenFervor/RTS/Selection/GardenFervorSelectionComponent.h',
      'Source/GardenFervor/RTS/Selection/GardenFervorSelectionComponent.cpp',
    ],
    sourceDocuments: [],
    evidence: [],
    confidence: 'HIGH',
  },
  {
    id: 'sys_input',
    name: 'Input (Enhanced + Player)',
    category: 'UI_INPUT',
    designStatus: 'PARTIAL',
    implementationStatus: 'IMPLEMENTED',
    validationStatus: 'n/a',
    responsibility: 'Entrées joueur Enhanced Input',
    sourceFiles: [
      'Source/GardenFervor/Input/GardenFervorPlayerInputComponent.h',
      'Source/GardenFervor/Input/GardenFervorEnhancedInputService.h',
      'Source/GardenFervor/Input/GardenFervorDeveloperSettings.h',
    ],
    sourceDocuments: [],
    evidence: [],
    confidence: 'HIGH',
  },
  {
    id: 'sys_rts_hud',
    name: 'RTSHUDWidget',
    category: 'UI_INPUT',
    designStatus: 'PARTIAL',
    implementationStatus: 'PARTIAL',
    validationStatus: 'n/a',
    responsibility: 'HUD RTS',
    sourceFiles: [
      'Source/GardenFervor/UI/GardenFervorRTSHUDWidget.h',
      'Source/GardenFervor/UI/GardenFervorRTSHUDWidget.cpp',
    ],
    sourceDocuments: [],
    evidence: [],
    confidence: 'HIGH',
  },
  {
    id: 'sys_visual_runtime_gate',
    name: 'VisualRuntimeGate',
    category: 'CONTENT_EXTERNAL',
    designStatus: 'VALIDÉ',
    implementationStatus: 'IMPLEMENTED',
    validationStatus: 'PASS',
    responsibility: 'Gate présentation M4/RVT/UDS',
    sourceFiles: [
      'Source/GardenFervor/RTS/Environment/GardenFervorVisualRuntimeGate.h',
      'Source/GardenFervor/RTS/Environment/GardenFervorVisualRuntimeGate.cpp',
    ],
    sourceDocuments: ['Saved/ODC_F2_VisualTerrainGate.txt'],
    evidence: ['evid_odc_f2'],
    confidence: 'HIGH',
  },
  {
    id: 'sys_game_framework',
    name: 'GameMode / GameState / PC / PS',
    category: 'GAME_DEMO',
    designStatus: 'PARTIAL',
    implementationStatus: 'IMPLEMENTED',
    validationStatus: 'n/a',
    responsibility: 'Framework jeu de base',
    sourceFiles: [
      'Source/GardenFervor/Game/GardenFervorGameMode.h',
      'Source/GardenFervor/Game/GardenFervorGameState.h',
      'Source/GardenFervor/Game/GardenFervorPlayerController.h',
      'Source/GardenFervor/Game/GardenFervorPlayerState.h',
    ],
    sourceDocuments: [],
    evidence: [],
    confidence: 'HIGH',
  },
  {
    id: 'sys_investor_demo',
    name: 'Investor Demo S3',
    category: 'GAME_DEMO',
    designStatus: 'VALIDÉ',
    implementationStatus: 'IMPLEMENTED',
    validationStatus: 'PASS',
    responsibility: 'Présentation investisseur ; consomme Project/Task/Units/PE',
    sourceFiles: [
      'Source/GardenFervor/Game/GardenFervorInvestorDemoS3Director.h',
      'Source/GardenFervor/Game/GardenFervorInvestorDemoS3Director.cpp',
      'Source/GardenFervor/Game/GardenFervorInvestorDemoGameMode.h',
      'Source/GardenFervor/Game/GardenFervorInvestorDemoPlayerController.h',
    ],
    sourceDocuments: ['ETAT_PROJET.md'],
    evidence: ['evid_s3_cohort'],
    confidence: 'HIGH',
  },
  {
    id: 'sys_case_b',
    name: 'Case B RequiresTerraform',
    category: 'PROJECTS_TASKS',
    designStatus: 'PARTIAL',
    implementationStatus: 'SUSPENDED',
    validationStatus: 'n/a',
    responsibility: 'Préparation terrain obligatoire avant WorkSite (suspendu)',
    sourceFiles: [
      'Source/GardenFervor/RTS/Projects/GardenFervorProjectSubsystem.cpp',
      'Source/GardenFervor/RTS/Projects/GardenFervorSitePrepHelpers.cpp',
    ],
    sourceDocuments: ['CONTRATS/00_REGISTRE_CONTRATS.md', 'CONTRATS/00_SUIVI_CONTRATS.md'],
    evidence: [],
    confidence: 'HIGH',
    notes: 'Code partiel présent ; évolution gameplay suspendue.',
  },

  // ——— DATA ———
  mkData('data_project_record', 'ProjectRecord', 'Enregistrement projet runtime', [
    'Source/GardenFervor/RTS/Projects/GardenFervorProjectTypes.h',
  ]),
  mkData('data_task_record', 'TaskRecord', 'Enregistrement tâche (états, prereqs, claim, progress)', [
    'Source/GardenFervor/RTS/Tasks/GardenFervorTaskTypes.h',
  ]),
  mkData('data_spatial_cell', 'SpatialCell / queries', 'Cellules + QueryTerrain/Soil/Water', [
    'Source/GardenFervor/RTS/Spatial/GardenFervorSpatialTypes.h',
  ]),
  mkData('data_height_store', 'Height Store (Base/Delta)', 'Vérité hauteur runtime (cible shipping)', [
    'Source/GardenFervor/RTS/Terraform/GardenFervorRuntimeTerraformStore.h',
  ]),
  mkData('data_stock', 'Physical Stock', 'Stock localisé + ResourceKey', [
    'Source/GardenFervor/RTS/Economy/GardenFervorPhysicalEconomySubsystem.h',
    'Source/GardenFervor/RTS/Economy/GardenFervorPhysicalResourceTypes.h',
  ]),
  mkData('data_reservation', 'Task Reservation', 'Réservation liée à une tâche', [
    'Source/GardenFervor/RTS/Tasks/GardenFervorTaskTypes.h',
  ]),
  mkData('data_capabilities', 'Unit Capabilities', 'Capacités abstraites d’unité', [
    'Source/GardenFervor/RTS/Data/GardenFervorUnitCapabilityTypes.h',
  ]),

  // ——— EVIDENCE ———
  mkEvidence('evid_odc_f1', 'ODC-F1 Runtime terrain', 'INVALIDÉ', 'Saved/ODC_F1_RuntimeTerrainGate.txt'),
  mkEvidence('evid_odc_f2', 'ODC-F2 Visual terrain (M4/UDS)', 'PASS', 'Saved/ODC_F2_VisualTerrainGate.txt'),
  mkEvidence('evid_odc_f3', 'ODC-F3 Spatial substrate', 'PASS', 'Saved/ODC_F3_SimulationSubstrateGate.txt'),
  mkEvidence('evid_odc_f4', 'ODC-F4 Task graph', 'PASS', 'Saved/ODC_F4_TaskGraphGate.txt'),
  mkEvidence('evid_odc_f5', 'ODC-F5 Autonomy', 'PASS', 'Saved/ODC_F5_AutonomyGate.txt'),
  mkEvidence('evid_odc_f6', 'ODC-F6 Physical economy', 'PASS', 'Saved/ODC_F6_EconomyGate.txt'),
  mkEvidence('evid_odc_f7', 'ODC-F7 Logistics', 'PASS', 'Saved/ODC_F7_LogisticsGate.txt'),
  mkEvidence('evid_odc_f8', 'ODC-F8 Terraform operation', 'PASS', 'Saved/ODC_F8_TerraformOperationGate.txt'),
  {
    id: 'evid_s3_cohort',
    name: 'Cohorte S3 Cas A (T1–T9)',
    category: 'VALIDATION',
    designStatus: 'VALIDÉ',
    implementationStatus: 'IMPLEMENTED',
    validationStatus: 'PASS',
    responsibility: 'Validation humaine end-to-end Cas A WorkSite',
    sourceDocuments: ['ETAT_PROJET.md', 'HISTORIQUE_MODIFICATIONS.md'],
    sourceFiles: [],
    evidence: [],
    confidence: 'HIGH',
    notes: '9/9 tranches VALIDÉ ; Case B hors périmètre.',
  },

  // ——— EXTERNAL ———
  {
    id: 'ext_m4',
    name: 'MagicMapMaterial (M4)',
    category: 'CONTENT_EXTERNAL',
    designStatus: 'VALIDÉ',
    implementationStatus: 'IMPLEMENTED',
    validationStatus: 'PASS',
    responsibility: 'Présentation terrain / RVT (non vérité gameplay)',
    sourceDocuments: ['Saved/ODC_F2_VisualTerrainGate.txt'],
    sourceFiles: ['Content/M4/'],
    evidence: ['evid_odc_f2'],
    confidence: 'HIGH',
  },
  {
    id: 'ext_uds',
    name: 'Ultra Dynamic Sky',
    category: 'CONTENT_EXTERNAL',
    designStatus: 'VALIDÉ',
    implementationStatus: 'IMPLEMENTED',
    validationStatus: 'PASS',
    responsibility: 'Ciel / environnement présentation',
    sourceDocuments: ['Saved/ODC_F2_VisualTerrainGate.txt'],
    sourceFiles: ['Content/UltraDynamicSky/'],
    evidence: ['evid_odc_f2'],
    confidence: 'HIGH',
  },
  {
    id: 'ext_ue_plugins',
    name: 'Plugins UE (EnhancedInput, Landmass, VHM, PMC…)',
    category: 'CONTENT_EXTERNAL',
    designStatus: 'n/a',
    implementationStatus: 'IMPLEMENTED',
    validationStatus: 'n/a',
    responsibility: 'Plugins activés dans GardenFervor.uproject',
    sourceDocuments: ['GardenFervor.uproject'],
    sourceFiles: ['GardenFervor.uproject'],
    evidence: [],
    confidence: 'HIGH',
  },

  // ——— TOOLING ———
  {
    id: 'tool_docs_pages',
    name: 'docs / GitHub Pages sync',
    category: 'TOOLING',
    designStatus: 'n/a',
    implementationStatus: 'IMPLEMENTED',
    validationStatus: 'n/a',
    responsibility: 'Hub docs, presentation, syncPages',
    sourceDocuments: ['docs/GITHUB_PAGES.md'],
    sourceFiles: ['docs/syncPages.mjs', 'docs/index.html'],
    evidence: [],
    confidence: 'HIGH',
  },
  {
    id: 'tool_designgate_react',
    name: 'Design Gate React app',
    category: 'TOOLING',
    designStatus: 'VALIDÉ',
    implementationStatus: 'IMPLEMENTED',
    validationStatus: 'n/a',
    responsibility: 'UI interactive Design Gate',
    sourceDocuments: [],
    sourceFiles: ['GardenFervor_DesignGate_React/'],
    evidence: [],
    confidence: 'HIGH',
  },
  {
    id: 'tool_project_graph',
    name: 'PROJECT_GRAPH (cette cartographie)',
    category: 'TOOLING',
    designStatus: 'n/a',
    implementationStatus: 'IMPLEMENTED',
    validationStatus: 'n/a',
    responsibility: 'Projection documentaire de l’architecture',
    sourceDocuments: ['PROJECT_GRAPH/README.md'],
    sourceFiles: ['PROJECT_GRAPH/'],
    evidence: [],
    confidence: 'HIGH',
  },
];

/**
 * @type {Array<object>}
 */
export const curatedEdges = [
  // Governance
  e('gov_regles', 'dg_hub', 'GOVERNS', 'HIGH', 'REGLES_PROJET.md'),
  e('gov_etat', 'gov_registre_contrats', 'READS', 'HIGH', 'ETAT_PROJET.md'),
  e('gov_suivi_contrats', 'gov_registre_contrats', 'DEPENDS_ON', 'HIGH', 'CONTRATS/00_SUIVI_CONTRATS.md'),
  e('gov_registre_contrats', 'c_01', 'GOVERNS', 'HIGH', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('gov_registre_contrats', 'c_02', 'GOVERNS', 'HIGH', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('gov_registre_contrats', 'c_04', 'GOVERNS', 'HIGH', 'CONTRATS/00_REGISTRE_CONTRATS.md'),

  // DG → contracts / systems
  e('dg_hub', 'dg_00', 'OWNS', 'HIGH', 'GardenFervor_DesignGate_React/src/data/designGate.js'),
  e('dg_hub', 'dg_04', 'OWNS', 'HIGH', 'GardenFervor_DesignGate_React/src/data/designGate.js'),
  e('dg_hub', 'dg_05', 'OWNS', 'HIGH', 'GardenFervor_DesignGate_React/src/data/designGate.js'),
  e('dg_hub', 'dg_06', 'OWNS', 'HIGH', 'GardenFervor_DesignGate_React/src/data/designGate.js'),
  e('dg_hub', 'dg_08', 'OWNS', 'HIGH', 'GardenFervor_DesignGate_React/src/data/designGate.js'),
  e('dg_hub', 'dg_09', 'OWNS', 'HIGH', 'GardenFervor_DesignGate_React/src/data/designGate.js'),
  e('dg_hub', 'dg_11', 'OWNS', 'HIGH', 'GardenFervor_DesignGate_React/src/data/designGate.js'),
  e('dg_hub', 'dg_11_6', 'OWNS', 'HIGH', 'GardenFervor_DesignGate_React/src/data/designGate.js'),
  e('dg_hub', 'dg_13', 'OWNS', 'HIGH', 'GardenFervor_DesignGate_React/src/data/designGate.js'),
  e('dg_00', 'c_00', 'GOVERNS', 'HIGH', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('dg_08', 'c_01', 'GOVERNS', 'HIGH', 'CONTRATS/C-01_TERRAIN_RUNTIME.md'),
  e('dg_08', 'c_02', 'GOVERNS', 'HIGH', 'CONTRATS/C-02_SUBSTRAT_SPATIAL.md'),
  e('dg_08', 'c_08', 'GOVERNS', 'MEDIUM', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('dg_11', 'c_04', 'GOVERNS', 'MEDIUM', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('dg_11', 'c_05', 'GOVERNS', 'MEDIUM', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('dg_04', 'c_07', 'GOVERNS', 'MEDIUM', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('dg_05', 'c_09', 'GOVERNS', 'MEDIUM', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('dg_05', 'c_11', 'GOVERNS', 'MEDIUM', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('dg_06', 'c_12', 'GOVERNS', 'MEDIUM', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('dg_09', 'c_15', 'GOVERNS', 'MEDIUM', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('dg_09', 'c_16', 'GOVERNS', 'MEDIUM', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('dg_09', 'c_17', 'GOVERNS', 'MEDIUM', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('dg_11_6', 'c_04', 'CONSTRAINS', 'MEDIUM', 'GardenFervor_DesignGate_React/src/data/designGate.js', {
    relationKind: 'FUTURE',
    notes: 'DG-11.6 = chantier ; C-04 = mécanisme tâche — complémentaire, pas encore câblé runtime.',
  }),

  // Contract → systems
  e('c_01', 'sys_runtime_store', 'GOVERNS', 'HIGH', 'CONTRATS/C-01_TERRAIN_RUNTIME.md'),
  e('c_01', 'sys_landscape_terraform', 'CONSTRAINS', 'HIGH', 'CONTRATS/C-01_TERRAIN_RUNTIME.md'),
  e('c_01', 'sys_base_height', 'GOVERNS', 'HIGH', 'CONTRATS/C-01_TERRAIN_RUNTIME.md'),
  e('c_01', 'sys_terraform_visualizer', 'CONSTRAINS', 'HIGH', 'CONTRATS/C-01_TERRAIN_RUNTIME.md'),
  e('c_01', 'sys_terraform_save', 'CONSTRAINS', 'HIGH', 'CONTRATS/C-01_TERRAIN_RUNTIME.md'),
  e('c_02', 'sys_spatial', 'GOVERNS', 'HIGH', 'CONTRATS/C-02_SUBSTRAT_SPATIAL.md'),
  e('c_02', 'data_spatial_cell', 'OWNS', 'HIGH', 'CONTRATS/C-02_SUBSTRAT_SPATIAL.md'),
  e('c_05', 'sys_siteprep', 'GOVERNS', 'MEDIUM', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('c_04', 'sys_task', 'GOVERNS', 'MEDIUM', 'CONTRATS/00_REGISTRE_CONTRATS.md', {
    notes: 'Gouvernance cible ; contrat C-04 pas encore VALIDÉ.',
  }),
  e('c_07', 'sys_unit_agent', 'GOVERNS', 'MEDIUM', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('c_08', 'sys_terraform_tool', 'GOVERNS', 'MEDIUM', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('c_09', 'sys_physical_economy', 'GOVERNS', 'MEDIUM', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('c_23', 'ext_m4', 'CONSTRAINS', 'MEDIUM', 'CONTRATS/00_REGISTRE_CONTRATS.md', {
    notes: 'M4 = rendu ; gameplay terrain reste C-01.',
  }),

  // Contract dependencies (registre)
  e('c_02', 'c_01', 'DEPENDS_ON', 'HIGH', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('c_04', 'c_03', 'DEPENDS_ON', 'HIGH', 'CONTRATS/00_REGISTRE_CONTRATS.md', {
    notes: 'Amont officiel ; C-03 addendum fermé (S3 suffit).',
  }),
  e('c_05', 'c_01', 'DEPENDS_ON', 'HIGH', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('c_05', 'c_04', 'DEPENDS_ON', 'HIGH', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('c_07', 'c_04', 'DEPENDS_ON', 'HIGH', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('c_07', 'c_06', 'DEPENDS_ON', 'HIGH', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('c_08', 'c_01', 'DEPENDS_ON', 'HIGH', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('c_08', 'c_05', 'DEPENDS_ON', 'HIGH', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('c_08', 'c_07', 'DEPENDS_ON', 'HIGH', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('c_11', 'c_04', 'DEPENDS_ON', 'HIGH', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('c_11', 'c_09', 'DEPENDS_ON', 'HIGH', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('c_11', 'c_10', 'DEPENDS_ON', 'HIGH', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('c_12', 'c_07', 'DEPENDS_ON', 'HIGH', 'CONTRATS/00_REGISTRE_CONTRATS.md'),
  e('c_12', 'c_10', 'DEPENDS_ON', 'HIGH', 'CONTRATS/00_REGISTRE_CONTRATS.md'),

  // Runtime dataflow (observed in code)
  e('sys_landscape_terraform', 'data_height_store', 'WRITES', 'HIGH', 'Source/GardenFervor/RTS/Terraform/GardenFervorLandscapeTerraformSubsystem.cpp'),
  e('sys_landscape_terraform', 'sys_spatial', 'SIGNALS', 'HIGH', 'Source/GardenFervor/RTS/Terraform/GardenFervorLandscapeTerraformSubsystem.cpp', {
    notes: 'MarkDirtyLandscapeRect après brush (ODC-F3).',
  }),
  e('sys_spatial', 'data_spatial_cell', 'OWNS', 'HIGH', 'Source/GardenFervor/RTS/Spatial/GardenFervorSpatialSubsystem.h'),
  e('sys_spatial', 'sys_runtime_store', 'READS', 'HIGH', 'Source/GardenFervor/RTS/Spatial/GardenFervorSpatialSubsystem.cpp'),
  e('sys_project', 'data_project_record', 'OWNS', 'HIGH', 'Source/GardenFervor/RTS/Projects/GardenFervorProjectTypes.h'),
  e('sys_project', 'sys_task', 'PRODUCES', 'HIGH', 'Source/GardenFervor/RTS/Projects/GardenFervorProjectSubsystem.cpp', {
    notes: 'ExpandProjectToTasks / ExpandWorkSite / ExpandLevelPad.',
  }),
  e('sys_project', 'sys_siteprep', 'EXECUTES', 'HIGH', 'Source/GardenFervor/RTS/Projects/GardenFervorSitePrepHelpers.cpp'),
  e('sys_siteprep', 'sys_case_b', 'CONSTRAINS', 'HIGH', 'Source/GardenFervor/RTS/Projects/GardenFervorSitePrepHelpers.cpp'),
  e('sys_task', 'data_task_record', 'OWNS', 'HIGH', 'Source/GardenFervor/RTS/Tasks/GardenFervorTaskTypes.h'),
  e('sys_task', 'data_reservation', 'OWNS', 'HIGH', 'Source/GardenFervor/RTS/Tasks/GardenFervorTaskTypes.h'),
  e('sys_unit_agent', 'sys_task', 'CONSUMES', 'HIGH', 'Source/GardenFervor/RTS/Units/GardenFervorUnitTaskAgent.cpp'),
  e('sys_unit_agent', 'sys_task', 'EXECUTES', 'HIGH', 'Source/GardenFervor/RTS/Units/GardenFervorUnitTaskAgent.cpp', {
    notes: 'TryClaimTask, SetTaskProgress, CompleteTask.',
  }),
  e('sys_unit_agent', 'sys_physical_economy', 'WRITES', 'HIGH', 'Source/GardenFervor/RTS/Units/GardenFervorUnitTaskAgent.cpp'),
  e('sys_unit_agent', 'sys_terraform_tool', 'EXECUTES', 'HIGH', 'Source/GardenFervor/RTS/Units/GardenFervorUnitTaskAgent.cpp'),
  e('sys_unit_agent', 'data_capabilities', 'READS', 'HIGH', 'Source/GardenFervor/RTS/Units/GardenFervorUnitTaskAgent.cpp'),
  e('sys_terraform_tool', 'sys_landscape_terraform', 'WRITES', 'HIGH', 'Source/GardenFervor/RTS/Units/GardenFervorTerraformToolComponent.cpp'),
  e('sys_harvest', 'sys_physical_economy', 'WRITES', 'MEDIUM', 'Source/GardenFervor/RTS/Units/GardenFervorHarvestComponent.cpp'),
  e('sys_physical_economy', 'data_stock', 'OWNS', 'HIGH', 'Source/GardenFervor/RTS/Economy/GardenFervorPhysicalEconomySubsystem.h'),
  e('sys_unit_base', 'sys_unit_agent', 'OWNS', 'HIGH', 'Source/GardenFervor/RTS/Units/GardenFervorUnitBase.cpp'),
  e('sys_investor_demo', 'sys_project', 'CONSUMES', 'HIGH', 'Source/GardenFervor/Game/GardenFervorInvestorDemoS3Director.cpp'),
  e('sys_investor_demo', 'sys_task', 'READS', 'HIGH', 'Source/GardenFervor/Game/GardenFervorInvestorDemoS3Director.cpp'),
  e('sys_investor_demo', 'sys_physical_economy', 'READS', 'MEDIUM', 'Source/GardenFervor/Game/GardenFervorInvestorDemoS3Director.cpp'),

  // Frontiers / FUTURE invalidation
  e('sys_spatial', 'sys_task', 'SIGNALS', 'MEDIUM', 'CONTRATS/C-02_SUBSTRAT_SPATIAL.md', {
    relationKind: 'FUTURE',
    notes: 'C-02 localise Dirty ; consommation tâche non câblée (futur C-04 G4).',
  }),
  e('c_02', 'c_04', 'SIGNALS', 'MEDIUM', 'CONTRATS/C-02_SUBSTRAT_SPATIAL.md', {
    relationKind: 'FUTURE',
    notes: 'Frontière contractuelle cible ; C-04 non VALIDÉ.',
  }),
  e('c_04', 'c_05', 'CONSTRAINS', 'MEDIUM', 'CONTRATS/00_REGISTRE_CONTRATS.md', {
    relationKind: 'FUTURE',
    notes: 'C-05 décide SitePrep ; C-04 orchestre tâches résultantes.',
  }),
  e('c_04', 'c_07', 'CONSTRAINS', 'MEDIUM', 'CONTRATS/00_REGISTRE_CONTRATS.md', {
    relationKind: 'FUTURE',
    notes: 'C-07 exécute ; ne définit pas le graphe.',
  }),
  e('c_04', 'c_08', 'CONSTRAINS', 'MEDIUM', 'CONTRATS/00_REGISTRE_CONTRATS.md', {
    relationKind: 'FUTURE',
    notes: 'C-08 métier Terraform ; C-04 tâche générique.',
  }),
  e('c_04', 'c_11', 'CONSTRAINS', 'MEDIUM', 'CONTRATS/00_REGISTRE_CONTRATS.md', {
    relationKind: 'FUTURE',
    notes: 'C-04 mécanisme réservation tâche ; C-11 concurrence détaillée.',
  }),

  // Validation
  e('evid_odc_f1', 'sys_runtime_store', 'VALIDATES', 'HIGH', 'Saved/ODC_F1_RuntimeTerrainGate.txt', {
    notes: 'Résultat INVALIDÉ.',
  }),
  e('evid_odc_f2', 'ext_m4', 'VALIDATES', 'HIGH', 'Saved/ODC_F2_VisualTerrainGate.txt'),
  e('evid_odc_f2', 'ext_uds', 'VALIDATES', 'HIGH', 'Saved/ODC_F2_VisualTerrainGate.txt'),
  e('evid_odc_f2', 'sys_visual_runtime_gate', 'VALIDATES', 'HIGH', 'Saved/ODC_F2_VisualTerrainGate.txt'),
  e('evid_odc_f3', 'sys_spatial', 'VALIDATES', 'HIGH', 'Saved/ODC_F3_SimulationSubstrateGate.txt'),
  e('evid_odc_f4', 'sys_task', 'VALIDATES', 'HIGH', 'Saved/ODC_F4_TaskGraphGate.txt'),
  e('evid_odc_f4', 'sys_project', 'VALIDATES', 'HIGH', 'Saved/ODC_F4_TaskGraphGate.txt'),
  e('evid_odc_f5', 'sys_unit_agent', 'VALIDATES', 'HIGH', 'Saved/ODC_F5_AutonomyGate.txt'),
  e('evid_odc_f6', 'sys_physical_economy', 'VALIDATES', 'HIGH', 'Saved/ODC_F6_EconomyGate.txt'),
  e('evid_odc_f7', 'sys_unit_agent', 'VALIDATES', 'HIGH', 'Saved/ODC_F7_LogisticsGate.txt', {
    notes: 'Haul A→B via agent + PE.',
  }),
  e('evid_odc_f8', 'sys_landscape_terraform', 'VALIDATES', 'HIGH', 'Saved/ODC_F8_TerraformOperationGate.txt'),
  e('evid_odc_f8', 'sys_terraform_tool', 'VALIDATES', 'HIGH', 'Saved/ODC_F8_TerraformOperationGate.txt'),
  e('evid_s3_cohort', 'sys_project', 'VALIDATES', 'HIGH', 'ETAT_PROJET.md'),
  e('evid_s3_cohort', 'sys_siteprep', 'VALIDATES', 'HIGH', 'ETAT_PROJET.md'),
  e('evid_s3_cohort', 'sys_investor_demo', 'VALIDATES', 'HIGH', 'ETAT_PROJET.md'),

  // External integration
  e('ext_m4', 'sys_landscape_terraform', 'VISUALIZES', 'HIGH', 'Saved/ODC_F2_VisualTerrainGate.txt', {
    notes: 'M4 présente Landscape ; ne remplace pas C-01.',
  }),
  e('ext_uds', 'sys_visual_runtime_gate', 'INTEGRATES_WITH', 'HIGH', 'Saved/ODC_F2_VisualTerrainGate.txt'),
  e('ext_ue_plugins', 'sys_input', 'INTEGRATES_WITH', 'HIGH', 'GardenFervor.uproject'),

  // Tooling
  e('tool_designgate_react', 'dg_hub', 'VISUALIZES', 'HIGH', 'GardenFervor_DesignGate_React/'),
  e('tool_docs_pages', 'sys_investor_demo', 'VISUALIZES', 'MEDIUM', 'docs/presentation-client.html'),
  e('tool_project_graph', 'gov_registre_contrats', 'READS', 'HIGH', 'PROJECT_GRAPH/README.md'),
];

function mkContract(id, code, name, contractNeed, docStatus, codeState, inCounter, file, extra = {}) {
  return {
    id,
    name: `${code} — ${name}`,
    category: 'CONTRACTS',
    designStatus: docStatus === 'VALIDÉ' ? 'VALIDÉ' : docStatus === 'NON COMMENCÉ' ? 'PLANNED' : docStatus,
    implementationStatus: mapCodeState(codeState),
    validationStatus: docStatus === 'VALIDÉ' ? 'PASS' : 'n/a',
    responsibility: `Contrat opérationnel ${code}`,
    sourceDocuments: file
      ? [file, 'CONTRATS/00_REGISTRE_CONTRATS.md', 'CONTRATS/00_SUIVI_CONTRATS.md']
      : ['CONTRATS/00_REGISTRE_CONTRATS.md', 'CONTRATS/00_SUIVI_CONTRATS.md'],
    sourceFiles: file ? [file] : [],
    evidence: [],
    confidence: 'HIGH',
    contractNeed,
    documentStatus: docStatus,
    inValidationCounter: inCounter,
    ...extra,
  };
}

function mapCodeState(s) {
  if (s === 'I') return 'IMPLEMENTED';
  if (s === 'P' || s === 'N/P') return 'PARTIAL';
  if (s === 'N') return 'PLANNED';
  if (s === 'V') return 'PLANNED';
  return 'UNKNOWN';
}

function mkData(id, name, responsibility, files) {
  return {
    id,
    name,
    category: 'DATA',
    designStatus: 'PARTIAL',
    implementationStatus: 'IMPLEMENTED',
    validationStatus: 'n/a',
    responsibility,
    sourceFiles: files,
    sourceDocuments: [],
    evidence: [],
    confidence: 'HIGH',
  };
}

function mkEvidence(id, name, validationStatus, path) {
  return {
    id,
    name,
    category: 'VALIDATION',
    designStatus: 'n/a',
    implementationStatus: 'n/a',
    validationStatus,
    responsibility: `Preuve ${name}`,
    sourceDocuments: [path],
    sourceFiles: [path],
    evidence: [],
    confidence: 'HIGH',
  };
}

function e(from, to, type, confidence, source, extra = {}) {
  return {
    id: `${from}__${type}__${to}${extra.relationKind ? '__' + extra.relationKind : ''}`,
    from,
    to,
    type,
    confidence,
    source,
    relationKind: extra.relationKind || 'ACTIVE',
    notes: extra.notes || '',
  };
}
